-- Japan 2026 - seed data
-- GENERATED by tools/generate-seed.py. Edit data/itinerary.json instead.
-- Run this fourth. Safe to re-run: everything is an upsert.

-- ------------------------------------------------------------- people
insert into people (id, name, short, colour, sort) values
  ('javier', 'Javier', 'J', '#2E4A6B', 0),
  ('rikke', 'Rikke', 'R', '#B0447A', 1),
  ('saga', 'Saga', 'S', '#D97706', 2),
  ('leo', 'Leo', 'L', '#2E8B57', 3)
on conflict (id) do update set
  name = excluded.name, short = excluded.short,
  colour = excluded.colour, sort = excluded.sort;

-- --------------------------------------------------------------- days
insert into days (position, kind, date, slug, leg, city, overnight, title, subtitle) values
  (0, 'pre', null, 'before', 'before', 'Home', null, 'Before We Go', 'Packing, predictions and counting down'),
  (1, 'day', '2026-09-15', null, 'inbound', 'Copenhagen to Tokyo', 'In flight', 'Departure Day', 'The long way east'),
  (2, 'day', '2026-09-16', null, 'shinjuku', 'Tokyo', 'Shinjuku', 'Arrival, Senso-ji and the First Konbini', 'Landing 07:55. Jet lag day, keep it gentle.'),
  (3, 'day', '2026-09-17', null, 'shinjuku', 'Tokyo', 'Shinjuku', 'Tsukiji, Gardens and the Skytree', 'Markets in the morning, the whole city at night'),
  (4, 'day', '2026-09-18', null, 'shinjuku', 'Tokyo', 'Shinjuku', 'Shrines, Harajuku and teamLab', 'Culture, pop culture, then the lights'),
  (5, 'day', '2026-09-19', null, 'kyoto', 'Kyoto', 'Gion', 'Shinkansen South, Then a Thousand Torii', 'Tokyo to Kyoto, and straight into the vermilion'),
  (6, 'day', '2026-09-20', null, 'kyoto', 'Kyoto', 'Gion', 'Gold, Zen and Bamboo', 'Northwest Kyoto and Arashiyama'),
  (7, 'day', '2026-09-21', null, 'kyoto', 'Kyoto', 'Gion', 'Nishiki Market and teamLab Kyoto', 'Kyoto''s kitchen, then the lights again'),
  (8, 'day', '2026-09-22', null, 'kyoto', 'Kyoto', 'Gion', 'Kiyomizu-dera and the Last Kyoto Day', 'Deep cuts before Osaka'),
  (9, 'day', '2026-09-23', null, 'osaka', 'Osaka', 'Namba', 'Osaka in Two Words: Eat Everything', 'Shinsekai, the castle, and then Dotonbori'),
  (10, 'day', '2026-09-24', null, 'osaka', 'Osaka', 'Namba', 'teamLab Osaka and Ura-Namba', 'Vintage streets by day, botanical lights by night'),
  (11, 'day', '2026-09-25', null, 'hiroshima', 'Hiroshima', 'Hiroshima', 'Peace Memorial Park', 'The reason for the stop. Don''t rush it.'),
  (12, 'day', '2026-09-26', null, 'miyajima', 'Miyajima', 'Ryokan, Miyajima', 'The Floating Torii', 'Deer, oysters, and the island after the day-trippers leave'),
  (13, 'day', '2026-09-27', null, 'kanazawa', 'Kanazawa', 'SOKI Kanazawa', 'The Long Leg North', 'Five hours of trains, then gold leaf'),
  (14, 'day', '2026-09-28', null, 'kanazawa', 'Kanazawa', 'SOKI Kanazawa', 'Kenroku-en, Ninja-dera and the Swimming Pool', 'A full Kanazawa day'),
  (15, 'day', '2026-09-29', null, 'kanazawa', 'Kanazawa', 'SOKI Kanazawa', 'Craft and Chill', 'Slow day before the mountains'),
  (16, 'day', '2026-09-30', null, 'takayama', 'Takayama', 'Takayama', 'Into the Alps', 'Old town, Hida beef, and mountain air'),
  (17, 'day', '2026-10-01', null, 'takayama', 'Takayama', 'Takayama', 'Morning Market and the Folk Village', 'A full Takayama day'),
  (18, 'day', '2026-10-02', null, 'kiso', 'Magome to Tsumago', 'Tokoname', 'The Nakasendo: Magome to Tsumago', 'Eight kilometres of the old road, then south to the pottery town'),
  (19, 'day', '2026-10-03', null, 'tokyo', 'Tokoname to Tokyo', 'Tokyo', 'Pottery Town, Then Back to the City', 'Kilns and maneki-neko before the shinkansen'),
  (20, 'day', '2026-10-04', null, 'tokyo', 'Tokyo', 'Tokyo', 'Unfinished Business', 'Whatever you missed the first time'),
  (21, 'day', '2026-10-05', null, 'tokyo', 'Tokyo', 'Tokyo', 'Last Full Day', 'Souvenirs, favourites, and the final dinner'),
  (22, 'day', '2026-10-06', null, 'outbound', 'Tokyo to Copenhagen', 'Home', 'Homeward', 'Early transfer to Haneda'),
  (23, 'post', null, 'after', 'after', 'Home', null, 'After', 'What we learned, ate, and would do again')
on conflict (position) do update set
  kind = excluded.kind, date = excluded.date, slug = excluded.slug,
  leg = excluded.leg, city = excluded.city, overnight = excluded.overnight,
  title = excluded.title, subtitle = excluded.subtitle;

