#!/usr/bin/env python3
"""Regenerate supabase/04_seed.sql from data/itinerary.json and data/people.json.

Run this whenever the itinerary changes, then re-run 04_seed.sql in Supabase.
It is safe to run repeatedly: every statement is an upsert keyed on position/id,
so it updates the 24 day rows without touching photos, meals or comments.

    python3 tools/generate-seed.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def q(value):
    """Quote a value as a SQL literal."""
    if value is None or value == "":
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    itinerary = json.loads((ROOT / "data" / "itinerary.json").read_text("utf-8"))
    people = json.loads((ROOT / "data" / "people.json").read_text("utf-8"))

    out = [
        "-- Japan 2026 - seed data",
        "-- GENERATED by tools/generate-seed.py. Edit data/itinerary.json instead.",
        "-- Run this fourth. Safe to re-run: everything is an upsert.",
        "",
        "-- ------------------------------------------------------------- people",
        "insert into people (id, name, short, colour, sort) values",
    ]

    rows = [
        "  ({}, {}, {}, {}, {})".format(
            q(p["id"]), q(p["name"]), q(p.get("short")), q(p["colour"]), i
        )
        for i, p in enumerate(people)
    ]
    out.append(",\n".join(rows))
    out.append(
        "on conflict (id) do update set\n"
        "  name = excluded.name, short = excluded.short,\n"
        "  colour = excluded.colour, sort = excluded.sort;"
    )
    out.append("")
    out.append("-- --------------------------------------------------------------- days")
    out.append(
        "insert into days (position, kind, date, slug, leg, city, overnight, title, subtitle) values"
    )

    day_rows = []
    for d in itinerary["days"]:
        day_rows.append(
            "  ({}, {}, {}, {}, {}, {}, {}, {}, {})".format(
                d["position"],
                q(d["kind"]),
                q(d.get("date")),
                q(d.get("slug")),
                q(d["leg"]),
                q(d.get("city")),
                q(d.get("overnight")),
                q(d["title"]),
                q(d.get("subtitle")),
            )
        )
    out.append(",\n".join(day_rows))
    out.append(
        "on conflict (position) do update set\n"
        "  kind = excluded.kind, date = excluded.date, slug = excluded.slug,\n"
        "  leg = excluded.leg, city = excluded.city, overnight = excluded.overnight,\n"
        "  title = excluded.title, subtitle = excluded.subtitle;"
    )
    out.append("")

    target = ROOT / "supabase" / "04_seed.sql"
    target.write_text("\n".join(out) + "\n", encoding="utf-8")

    travel = [d for d in itinerary["days"] if d["kind"] == "day"]
    print("Wrote {}".format(target.relative_to(ROOT)))
    print("  {} people".format(len(people)))
    print(
        "  {} days ({} travel days, {} to {})".format(
            len(itinerary["days"]), len(travel), travel[0]["date"], travel[-1]["date"]
        )
    )


if __name__ == "__main__":
    main()
